"Database":
  "username": "root"
  "password": ""
  "hostname": "127.0.0.1:3306"
  "dbname": "herosgame"

"Account":
  "a1":
    "username": "tfyiran397496548"
    "password": "md5:bbb3ec062b9ed22548ecd1938a66949e"

"WX_APPTOKEN": "AT_vYeuEDdRy41tuBxjfoN22MS1eudEMAF8"
"WX_Topic":
  "a1": !!int '44261'
